package com.marsa.smarttrackerhub.ui.screens.investers

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.marsa.smarttrackerhub.data.dao.SettlementEntryWithName
import com.marsa.smarttrackerhub.data.entity.YearEndSettlement
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Generates a plain-text settlement / investor report and shares it via Android share sheet.
 *
 * Created by Muhammed Shafi on 19/02/2026.
 * Moro Hub
 * muhammed.poyil@morohub.com
 */
object InvestorReportExporter {

    private val dateFormat = SimpleDateFormat("dd MMM yyyy", Locale.ENGLISH)
    private val fileNameDateFormat = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.ENGLISH)

    /**
     * Builds a full settlement report for [shopName] covering all [settlements],
     * with per-investor [entriesBySettlement] (settlementId → entries).
     * Shares it as a plain-text file via the Android share sheet.
     */
    fun shareSettlementReport(
        context: Context,
        shopName: String,
        settlements: List<YearEndSettlement>,
        entriesBySettlement: Map<Int, List<SettlementEntryWithName>>
    ) {
        val report = buildSettlementReport(shopName, settlements, entriesBySettlement)
        shareAsTextFile(context, report, "settlement_report_${fileNameDateFormat.format(Date())}.txt")
    }

    // ── Report builder ────────────────────────────────────────────────────

    private fun buildSettlementReport(
        shopName: String,
        settlements: List<YearEndSettlement>,
        entriesBySettlement: Map<Int, List<SettlementEntryWithName>>
    ): String {
        val sb = StringBuilder()

        sb.appendLine("=".repeat(52))
        sb.appendLine("  INVESTOR SETTLEMENT REPORT")
        sb.appendLine("  Shop : $shopName")
        sb.appendLine("  Date : ${dateFormat.format(Date())}")
        sb.appendLine("=".repeat(52))
        sb.appendLine()

        if (settlements.isEmpty()) {
            sb.appendLine("No settlements recorded.")
            return sb.toString()
        }

        settlements.forEachIndexed { index, settlement ->
            val periodStart = if (settlement.periodStartDate == 0L) "Beginning"
            else dateFormat.format(Date(settlement.periodStartDate))
            val periodEnd = dateFormat.format(Date(settlement.settlementDate))

            sb.appendLine("Settlement ${index + 1}")
            sb.appendLine("-".repeat(40))
            sb.appendLine("  Date       : $periodEnd")
            sb.appendLine("  Period     : $periodStart → $periodEnd")
            sb.appendLine("  Total Inv  : AED ${String.format("%,.2f", settlement.totalInvested)}")
            if (settlement.note.isNotBlank()) {
                sb.appendLine("  Note       : ${settlement.note}")
            }
            sb.appendLine()

            val entries = entriesBySettlement[settlement.id] ?: emptyList()
            if (entries.isEmpty()) {
                sb.appendLine("  (No investor entries)")
            } else {
                sb.appendLine("  Investor Breakdown:")
                entries.forEach { entry ->
                    val balanceSign = if (entry.balanceAmount >= 0) "+" else ""
                    val settledStatus = when {
                        entry.balanceAmount == 0.0 -> "Settled"
                        entry.settlementPaidAmount > 0.0 -> {
                            val paidDate = entry.settlementPaidDate?.let {
                                " on ${dateFormat.format(Date(it))}"
                            } ?: ""
                            "Paid AED ${String.format("%,.2f", entry.settlementPaidAmount)}$paidDate"
                        }
                        else -> "Outstanding"
                    }
                    sb.appendLine("  ┌─ ${entry.investorName}")
                    sb.appendLine("  │  Fair Share : AED ${String.format("%,.2f", entry.fairShareAmount)}")
                    sb.appendLine("  │  Actual Paid: AED ${String.format("%,.2f", entry.actualPaidAmount)}")
                    sb.appendLine("  │  Balance    : ${balanceSign}AED ${String.format("%,.2f", entry.balanceAmount)}")
                    sb.appendLine("  └─ Status     : $settledStatus")
                    sb.appendLine()
                }
            }

            sb.appendLine()
        }

        sb.appendLine("=".repeat(52))
        sb.appendLine("  Generated by TrackerHub")
        sb.appendLine("=".repeat(52))

        return sb.toString()
    }

    // ── File share helper ─────────────────────────────────────────────────

    private fun shareAsTextFile(context: Context, content: String, fileName: String) {
        try {
            val cacheDir = File(context.cacheDir, "reports").also { it.mkdirs() }
            val file = File(cacheDir, fileName)
            file.writeText(content, Charsets.UTF_8)

            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, "Settlement Report")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            context.startActivity(Intent.createChooser(intent, "Share Report"))
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
